name: ${project.name}
main: com.volmit.skyprime.SkyPrime
version: 1.0
commands:
  skyprime:
    aliases: [sky, sp, sprime]
permissions:
  sky.*:
    description: Gives access to all Sky permissions
    default: op
    children:
      sky.bypass: true
      sky.reload: true
  sky.bypass:
    description: Gives access to bypass permissions on other islands
    default: op
  sky.reload:
    description: Gives access to reload skyprime
    default: op