version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: circleci-project-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline -Pci
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-project-{{ checksum "pom.xml" }}
      - run: mvn package -Pci
      - store_artifacts:
          path: target/SkyPrime-production.jar